name: Parallel Steps
description: GitHub Action to run multiple steps in parallel
author: qoomon
branding:
  icon: grid
  color: blue

inputs:
  token:
    description: GitHub token
    default: ${{ github.token }}
    required: true
  steps:
    description: Parallel steps to run
    required: true
  defaults:
    description: Default settings that will apply to all steps
    required: false

# outputs:
#   <step id>-<output name>:
#     description: See the documentation for the step

runs:
  using: node20
  main: main.js
  post: post.js
