on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: qoomon/actions--parallel-steps@main
        with:
          steps: |
            - run: echo Step0
            - run: echo Step1
            - run: |
                echo Step2
                pwd
                echo Step2 > step2.txt
                ls -lachs
            - run: |
                echo Step3
            - run: echo Step4
            - run: echo Step5
            - run: echo Step6
            - run: echo Step7
            - uses: actions/github-script@v7
              with:
                script: console.log('Step8')
      - run: ls -lachs
