on:
  workflow_dispatch:
  push:

jobs:
  run:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: qoomon/actions--parallel-steps@main
        id: parallel-steps
        with:
          steps: |
            - run: | 
                echo "::group::xxx"
                echo GITHUB_ACTION=$GITHUB_ACTION
                echo "::endgroup::"
            - uses: actions/checkout@v4
            - name : Test File Creation
              run: |
                echo Step1
                echo Step1 > test-file.txt
            - name : Test Command Files
              id: command-file
              uses: actions/github-script@v7
              with:
                script: |
                  core.exportVariable('TEST_VARIABLE', 'AAA')
                  core.setOutput('test-output', 'BBB')
                  core.addPath('./test-command')
      #            - uses: actions/setup-java@v4
      #              with:
      #                distribution: 'temurin' # See 'Supported distributions' for available options
      #                java-version: '21'
      - run: |
          ls -lachs
          echo "TEST_VARIABLE:                                         $TEST_VARIABLE"
          echo "steps.parallel-steps.outputs.test-output:              ${{ steps.parallel-steps.outputs.test-output }}"
          echo "steps.parallel-steps.outputs.command-file.test-output: ${{ steps.parallel-steps.outputs.command-file-test-output }}"
          
            

