on:
  workflow_dispatch:
  push:

jobs:
  run:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: qoomon/actions--parallel-steps@main
        id: parallel
        with:
          steps: |
            - run: |
                echo Step0
            - name : Test File Creation
              run: |
                echo Step1
                echo Step1 > test-file.txt
            - name : Test Command Files
              uses: actions/github-script@v7
              with:
                script: |
                  console.log('Step2')
                  core.setOutput('test-output', 'Step2')
                  core.exportVariable('TEST_VARIABLE', 'Step2')
                  core.addPath('./test-path')
                  await core.summary
                    .addHeading('Test Results')
                    // TODO .addCodeBlock(generateTestResults(), "js")
                    .addTable([
                    [{data: 'File', header: true}, {data: 'Result', header: true}],
                    ['foo.js', 'Pass ✅'],
                    ['bar.js', 'Fail ❌'],
                    ['test.js', 'Pass ✅']
                  ])
                    .addLink('View staging deployment!', 'https://github.com')
                    .write()

      - run: |
          ls -lachs
          echo TEST_VARIABLE: $TEST_VARIABLE
          echo test-output: ${{ steps.parallel.outputs.test-output }}

