on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        env:
          FOO: 42
      - uses: qoomon/actions--parallel-steps@main
        id: parallel
        with:
          steps: |
            - run: echo Step0
            - run: echo Step1
            - run: |
                echo Step2
                pwd
                echo Step2 > step2.txt
                ls -lachs
            - run: |
                echo Step3
            - run: echo Step4
            - run: echo Step5
            - run: echo Step6
            - run: echo Step7
            - uses: actions/github-script@v7
              id: step8
              with:
                script: |
                  console.log('Step8')
                  core.setOutput('value8', 'Step8')
                  core.exportVariable('VALUE_8', 'Step8')
      - run: |
          ls -lachs
          echo VALUE_8 $VALUE_8
          echo OUTPUT_VALUE_8 OUTPUT_VALUE_8
        env:
          OUTPUT_VALUE_8: ${{ steps.parallel.outputs.step8-value8 }}

