name: Step 1
on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          steps: |
            - run: echo Step0
            - run: echo Step1
            - run: echo Step2
            - run: echo Step3
            - run: echo Step4
            - run: echo Step5
            - run: echo Step6
            - run: echo Step7
            - uses: actions/github-script@v7
              with:
                script: console.log('Step8')
