on:
  workflow_dispatch:
  push:

jobs:
  run:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:

      - uses: qoomon/actions--parallel-steps@main
        id: parallel-steps
        with:
          steps: |
            - uses: actions/checkout@v4
            - name : Test File Creation
              needs: [0]
              run: |
                echo Step1
                echo Step1 > test-file.txt
            - name : Test Command Files
              id: command-file
              uses: actions/github-script@v7
              with:
                script: |
                  core.info('This is a info')
                  core.notice('This is a notice')
                  core.warning('This is a warning')
                  core.error('This is a error')
                  core.debug('This is a dbug')
            
                  core.startGroup('A Group')
                    core.info('This is a info')
                    core.notice('This is a notice')
                    core.warning('This is a warning')
                    core.error('This is a error')
                    core.debug('This is a dbug')
                  core.endGroup()
                  
                  core.addPath('./test-command-CCC')
                  core.exportVariable('TEST_VARIABLE', 'AAA')
                  core.setOutput('test-output', 'BBB')
                  core.addPath('./test-command-CCC')
                  core.summary.addHeading('Test Summary').write()
      #            - uses: actions/setup-java@v4
      #              with:
      #                distribution: 'temurin' # See 'Supported distributions' for available options
      #                java-version: '21'
      - run: |
          ls -lachs
          echo "TEST_VARIABLE:                                         $TEST_VARIABLE"
          echo "steps.parallel-steps.outputs.test-output:              ${{ steps.parallel-steps.outputs.test-output }}"
          echo "steps.parallel-steps.outputs.command-file--test-output: ${{ steps.parallel-steps.outputs.command-file--test-output }}"
          
            

