on: workflow_dispatch

jobs:
  run :
    runs-on: host
    steps:
      - run: pwd
      - uses: actions/checkout@v4
      - uses: ./
        with:
          steps: |
            - run: echo Step0
            - run: |
                echo Step1 && sleep 2
            - run: |
                echo Step2
                echo Step2 > step2.txt
                echo FOO=step2 >> $GITHUB_ENV
            - uses: actions/github-script@v7
              with:
                script: |
                  console.log('Step4')
                  core.setOutput('step4', 'Step4')
      - run: |
          cat step2.txt
          echo FOO=$FOO
